name: Build and Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: dance-competition-app/package-lock.json

      - name: Install dependencies
        working-directory: dance-competition-app
        run: npm ci

      - name: Run ESLint
        working-directory: dance-competition-app
        run: npm run lint
        continue-on-error: true

      - name: Run TypeScript type check
        working-directory: dance-competition-app
        run: npx tsc --noEmit

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: dance-competition-app/package-lock.json

      - name: Install dependencies
        working-directory: dance-competition-app
        run: npm ci

      - name: Run tests
        working-directory: dance-competition-app
        run: npm test
        continue-on-error: true

      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: dance-competition-app/coverage/
          retention-days: 30

  build:
    name: Build with EAS
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: dance-competition-app/package-lock.json

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        working-directory: dance-competition-app
        run: npm ci

      - name: Build app with EAS
        working-directory: dance-competition-app
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            eas build --platform all --profile production --non-interactive
          else
            eas build --platform all --profile preview --non-interactive
          fi
        env:
          EXPO_PUBLIC_SUPABASE_URL: ${{ secrets.EXPO_PUBLIC_SUPABASE_URL }}
          EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.EXPO_PUBLIC_SUPABASE_ANON_KEY }}
